PGMG/Models/EstadoLlamada.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace PGMG.Models
{
    public class EstadoLlamada
    {
        public int EstadoLlamadaId { get; set; }
        [Display(Name = "Descripción")]
        public string Descripcion { get; set; }

    }
}

PGMG/Controllers/EstadoLlamadasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PGMG.Models;

namespace PGMG.Controllers
{
    [Authorize(Roles = "Administradora")]
    public class EstadoLlamadasController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: EstadoLlamadas
        public ActionResult Index()
        {
            return View(db.EstadosLlamadas.ToList());
        }

        // GET: EstadoLlamadas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EstadoLlamada estadoLlamada = db.EstadosLlamadas.Find(id);
            if (estadoLlamada == null)
            {
                return HttpNotFound();
            }
            return View(estadoLlamada);
        }

        // GET: EstadoLlamadas/Create
        public ActionResult Create()
        {
            return PartialView();
        }

        // POST: EstadoLlamadas/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "EstadoLlamadaId,Descripcion")] EstadoLlamada estadoLlamada)
        {
            if (ModelState.IsValid)
            {
                db.EstadosLlamadas.Add(estadoLlamada);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(estadoLlamada);
        }

        // GET: EstadoLlamadas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EstadoLlamada estadoLlamada = db.EstadosLlamadas.Find(id);
            if (estadoLlamada == null)
            {
                return HttpNotFound();
            }
            return PartialView(estadoLlamada);
        }

        // POST: EstadoLlamadas/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "EstadoLlamadaId,Descripcion")] EstadoLlamada estadoLlamada)
        {
            if (ModelState.IsValid)
            {
                db.Entry(estadoLlamada).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(estadoLlamada);
        }

        // GET: EstadoLlamadas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EstadoLlamada estadoLlamada = db.EstadosLlamadas.Find(id);
            if (estadoLlamada == null)
            {
                return HttpNotFound();
            }
            return PartialView(estadoLlamada);
        }

        // POST: EstadoLlamadas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            EstadoLlamada estadoLlamada = db.EstadosLlamadas.Find(id);
            db.EstadosLlamadas.Remove(estadoLlamada);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PGMG/Views/EstadoLlamadas/Create.cshtml
@model PGMG.Models.EstadoLlamada

@{
    ViewBag.Title = "Cargar nuevo estado llamada";
}


<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal"
            <span>&times;</span>
    </button>
</div>
<div class="modal-body centrar">
    <dl class="dl-horizontal">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label" })
                <br />
                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "login" } })
                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-default" data-target="#modal-crear" data-toggle="modal" />
                <input type="button" value="Cancelar" class="btn btn-default" data-target="#modal-crear" data-toggle="modal" />
            </div>

        }
    </dl>
</div>


@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        function closeModal(data) {
            if (data.success) {
                $('#modal-crear').modal('hide');
                window.location.href = "/EstadoLlamadas/index";
            }
        }
    </script>
}

PGMG/Views/EstadoLlamadas/Delete.cshtml
@model PGMG.Models.EstadoLlamada

@{
    ViewBag.Title = "Eliminar";
}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal"
        <span>&times;</span>
    </button>
</div>
<div class="modal-body">

    @using (Ajax.BeginForm("Delete", "EstadoLlamadas", null, new AjaxOptions
    {
        HttpMethod = "POST",
        Url = Url.Action("Delete", "EstadoLlamadas"),
        UpdateTargetId = "modal-content",
        OnSuccess = "closeModal",
        InsertionMode = InsertionMode.Replace
    },
    new { @class = "form-horizontal", role = "form", id = "frmCrear" }))
    {
        @Html.AntiForgeryToken()
        <div class="centrar">

            <h4>¿Desea eliminar el estado de llamada?</h4>
            <br />

            <input type="submit" value="Eliminar" class="btn btn-default" data-target="#modal-eliminar" data-toggle="modal" />
            <input type="button" value="Cancelar" class="btn btn-default" data-target="#modal-eliminar" data-toggle="modal" />

        </div>
    }
</div>

@section Scripts{
    <script>

        function closeModal(data) {
            if (data.success) {
                $('#modal-eliminar').modal('hide');
                window.location.reload();
                window.location.href = "/EstadoLlamada/index";
            }
        }
    </script>
}

PGMG/Views/EstadoLlamadas/Details.cshtml
@model PGMG.Models.EstadoLlamada

@{
    ViewBag.Title = "Detalles";
}

<h3>Detalles</h3>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Modificar", "Edit", new { id = Model.EstadoLlamadaId }) |
    @Html.ActionLink("Regresar", "Index")
</p>

PGMG/Views/EstadoLlamadas/Edit.cshtml
@model PGMG.Models.EstadoLlamada

@{
    ViewBag.Title = "Editar";
}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal"
            <span>&times;</span>
    </button>
</div>
<div class="modal-body centrar">
    <dl class="dl-horizontal">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.EstadoLlamadaId)

                <div class="form-group">
                    @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label" })
                    <br />
                    @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "login" } })
                    @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    <input type="submit" value="Guardar" class="btn btn-default" data-target="#modal-editar" data-toggle="modal" />
                    <input type="button" value="Cancelar" class="btn btn-default" data-target="#modal-editar" data-toggle="modal" />
                </div>
            </div>
        }
    </dl>
</div>


@section Scripts{
    <script>
        function closeModal(data) {
            if (data.success) {
                $('#modal-editar').modal('hide');
                window.location.href = "/EstadoLlamadas/index";
            }
        }
    </script>
}

PGMG/Views/EstadoLlamadas/Index.cshtml
@model IEnumerable<PGMG.Models.EstadoLlamada>

@{
    ViewBag.Title = "Estados de llamadas solicitadas";
}
<body class="w3">
    <div class="centrar">
        <h4>@ViewBag.Title</h4>
        <hr />
        <a href="@Url.Action("Create")" class="btn btn-default"
           data-target="#modal-crear" data-toggle="modal">
            Nuevo estado de llamada
        </a>
        <br /><br />
        <div class="table-responsive">
            <table id="estados" class="table table-striped">
                <thead>
                    <tr>
                        <th style="text-align: center" onclick="sortTable(0)">Descripción</th>
                        <th style="text-align: center">Acciones</th>
                    </tr>
                </thead>
                <tbody>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Descripcion)
                            </td>
                            <td>
                                <a href="@Url.Action("Edit", new {id = item.EstadoLlamadaId})" class="btn btn-default"
                                   data-target="#modal-editar" data-toggle="modal" title="Editar estado llamada">
                                    <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                                </a>
                                <a href="@Url.Action("Delete", new { id=item.EstadoLlamadaId })" class="btn btn-default"
                                   data-target="#modal-eliminar" data-toggle="modal" title="Eliminar estado llamada">
                                    <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</body>
<div class="modal fade" id="modal-eliminar" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
        </div>
    </div>
</div>
<div class="modal fade" id="modal-editar" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
        </div>
    </div>
</div>
<div class="modal fade" id="modal-crear" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
        </div>
    </div>
</div>

@section Scripts{
    <script>
        function sortTable(n) {
            var table, rows, switching, i, x, y, shouldSwitch, dir, switchcount = 0;
            table = document.getElementById("estados");
            switching = true;
            dir = "asc";
            while (switching) {
                switching = false;
                rows = table.rows;
                for (i = 1; i < (rows.length - 1); i++) {
                    shouldSwitch = false;
                    x = rows[i].getElementsByTagName("TD")[n];
                    y = rows[i + 1].getElementsByTagName("TD")[n];
                    if (dir == "asc") {
                        if (x.innerHTML.toLowerCase() > y.innerHTML.toLowerCase()) {
                            shouldSwitch = true;
                            break;
                        }
                    } else if (dir == "desc") {
                        if (x.innerHTML.toLowerCase() < y.innerHTML.toLowerCase()) {
                            shouldSwitch = true;
                            break;
                        }
                    }
                }
                if (shouldSwitch) {
                    rows[i].parentNode.insertBefore(rows[i + 1], rows[i]);
                    switching = true;
                    switchcount++;
                } else {
                    if (switchcount == 0 && dir == "asc") {
                        dir = "desc";
                        switching = true;
                    }
                }
            }
        }
    </script>
}