PGMG/Models/Llamada.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace PGMG.Models
{
    public class Llamada
    {
        public int LlamadaId { get; set; }
        public int? LlamadaSolicitadaId { get; set; }
        
        public int ClienteId { get; set; }

        public Cliente Cliente { get; set; }

        [Required(ErrorMessage = "Debe ingresar un cliente")]
        [Display(Name = "Nombre del cliente")]
        public string NombreCliente { get; set; }

        [Required(ErrorMessage = "Debe ingresar una fecha")]
        public DateTime Fecha { get; set; }

       
        [Required(ErrorMessage = "Debe ingresar una hora")]
        public DateTime Hora { get; set; }

        [Required(ErrorMessage = "Debe ingresar el nombre del empleado")]
        [Display(Name = "Nombre del empleado")]
        public string NombreEmpleado { get; set; }


        [Display(Name = "Forma de comunicacion")]
        public int FormaDeComunicacionId { get; set; }
        
        [Display(Name = "Forma de comunicación")]
        public ICollection<FormaDeComunicacion> FormaDeComunicacion { get; set; }

        public string Tema { get; set; }

        [DataType(DataType.MultilineText)]
        public string Descripcion { get; set; }

        [Display(Name = "Codigos tareas")]
        public int CodigoTareaId { get; set; }

        [Display(Name = "Códigos de tareas")]
        public virtual ICollection<CodigoTarea> Codigo { get; set; }


        [Display(Name = "Duración del llamado")]
        public string TiempoEnLlamado { get; set; }

        [Display(Name = "Tiempo de gestión")]
    
        public string  TiempoPostLlamado { get; set; }

        public string Usuario { get; set; }

        //[Display(Name = "Estado de la llamada")]
        public int? EstadoId { get; set; }


        [Display(Name = "Estado de la llamada")]
        public Estado Estado { get; set;}
   
        public int? EtiquetaId { get; set; }

        [Display(Name = "Seleccione la prioridad")]
        public Etiqueta Etiqueta { get; set; }

        public int Activo { get; set; }
    }
}

PGMG/Models/LlamadaViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace PGMG.Models
{

    public class LlamadaViewModel
    {
        public int LlamadaId { get; set; }
        public int ClienteId { get; set; }
        public DateTime Fecha { get; set; }
        public DateTime Hora { get; set; }
        public string Usuario { get; set; }
        [Display(Name = "Cliente")]
        public string NombreC { get; set; }
        [Display(Name = "Empleado")]
        public string NombreE { get; set; }      
        public string Tema { get; set; }
        public string Descripcion { get; set; }
        public int Activo { get; set; }
        public string Estado { get; set; }
        public string Etiqueta { get; set; }
        public int EtiquetaId { get; set; }
        public int Cantidad { get; set; }
        public int Tiempo { get; set; }
        public int CodigoTareaId { get; set; }
        public string CodigoT { get; set; }
    }
}

PGMG/Models/ReporteLlamadasViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using MvcValidationExtensions.Attribute;

namespace PGMG.Models
{
    public class ReporteLlamadasViewModel
    {
        public int ClienteId { get; set; }
        [Display(Name = "Nombre cliente")]
        public string NombreCliente { get; set; }

        [Required(ErrorMessage = "Debe ingresar una fecha desde")]
        [LessThanEqualTo("Hasta", ErrorMessage = "La fecha desde no puede ser mayor a la fecha hasta.")]
        [Display(Name = "Fecha desde")]
        public DateTime Desde { get; set; }

        [GreaterThanEqualTo("Desde", ErrorMessage = "La fecha hasta no puede ser menor a la fecha desde.")]
        [Required(ErrorMessage = "Debe ingresar una fecha hasta")]
        [Display(Name = "Fecha hasta")] 
        public DateTime Hasta { get; set; }

        public string Usuario { get; set; }

    }
}

PGMG/Controllers/LlamadasController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using PGMG.Models;
using PagedList;
using System.Collections.Generic;

namespace PGMG.Controllers
{
    public class LlamadasController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Llamadas
        //Index de Llamadas en Curso
        public ActionResult Index(int? pageSize, int? page)
        {
            Llamada llamada = new Llamada();

            var query = (from l in db.Llamadas where l.Activo == 1
                         orderby l.Fecha descending
                         select new LlamadaViewModel
                                   {
                                    Fecha = l.Fecha,
                                    Hora = l.Hora,
                                    Usuario = l.Usuario,
                                    NombreC = l.NombreCliente,
                                    NombreE = l.NombreEmpleado
                                   }).ToList();

            pageSize = (pageSize ?? 20);
            page = (page ?? 1);
            var list = query.ToPagedList(page.Value, pageSize.Value);

            return View(list);
        }
        
        //Index de llamadas del día
        public ActionResult Index2(int? pageSize, int? page)
        { 
            var query = (from l in db.Llamadas
                         where DbFunctions.TruncateTime(l.Fecha) == DateTime.Today
                         orderby l.Hora descending
                         select new LlamadaViewModel
                         {
                             LlamadaId = l.LlamadaId,
                             Fecha = l.Fecha,
                             Hora = l.Hora,
                             Usuario = l.Usuario,
                             NombreC = l.NombreCliente,
                             NombreE = l.NombreEmpleado,
                             Tema = l.Tema
                         }).ToList();

            pageSize = (pageSize ?? 20);
            page = (page ?? 1);
            var list = query.ToPagedList(page.Value, pageSize.Value);

            return View(list);
        }

        //Index de pendientes
        [Authorize(Roles = "Administradora, Consultora")]
        public ActionResult IndexPendientes(int? pageSize, int? page)
        {
            Llamada llamada = new Llamada();

            var query = (from l in db.Llamadas
                         where l.EstadoId == 2
                         orderby l.Fecha descending

                         select new PendientesViewModel
                         {
                             LlamadaId = l.LlamadaId,
                             Fecha = l.Fecha,
                             Hora = l.Hora,
                             Usuario = l.Usuario,
                             NombreC = l.NombreCliente,
                             Tema = l.Tema,
                             Etiqueta = l.Etiqueta.Descripcion
                         }).ToList();

            pageSize = (pageSize ?? 20);
            page = (page ?? 1);
            ViewBag.PageSize = pageSize;
            var list = query.ToPagedList(page.Value, pageSize.Value);

            return View(list);
        }

        [Authorize(Roles = "Administradora, Consultora")]
        //Ultimas llamadas por cliente
        public ActionResult UltimasLlamadas(int? id, Llamada llamada)
        {
            var query = (from l in db.Llamadas
                         where l.Activo == 0
                         && l.ClienteId == id
                         && l.LlamadaId != llamada.LlamadaId

                         orderby l.Fecha descending
                         select new LlamadaViewModel
                         {
                             LlamadaId = l.LlamadaId,
                             ClienteId = l.ClienteId,
                             Fecha = l.Fecha,
                             Hora = l.Hora,
                             Usuario = l.Usuario,
                             NombreE = l.NombreEmpleado,
                             Tema = l.Tema,
                             Descripcion = l.Descripcion
                         }).Take(5);

            return PartialView(query);
        }

        public ActionResult ReporteLlamadas(int? id, int? pageSize, int? page, Llamada llamada)
        {
            var query = (from l in db.Llamadas
                         where  l.ClienteId == id
                         && l.LlamadaId != llamada.LlamadaId
                         && l.Activo == 0
                         && l.EstadoId == 1
                         orderby l.Fecha descending
                         select new LlamadaViewModel
                         {
                             LlamadaId = l.LlamadaId,
                             ClienteId = l.ClienteId,
                             Fecha = l.Fecha,
                             Hora = l.Hora,
                             Tema = l.Tema,
                             Descripcion = l.Descripcion,
                             Usuario = l.Usuario,
                             NombreE = l.NombreEmpleado,
                             Estado = l.Estado.Descripcion,
                             Etiqueta = l.Etiqueta.Descripcion                
                         }).ToList();

            pageSize = (pageSize ?? 50);
            page = (page ?? 1);
            ViewBag.PageSize = pageSize;
            var list = query.ToPagedList(page.Value, pageSize.Value);

            return View(list);
        }

        public ActionResult ReportePendientes(int? id, int? pageSize, int? page, Llamada llamada)
        {
            var query = (from l in db.Llamadas
                         where l.ClienteId == id
                         && l.LlamadaId != llamada.LlamadaId
                         && l.Activo == 0
                         && l.EstadoId == 2
                         orderby l.Fecha descending
                         select new LlamadaViewModel
                         {
                             LlamadaId = l.LlamadaId,
                             ClienteId = l.ClienteId,
                             Fecha = l.Fecha,
                             Hora = l.Hora,
                             Tema = l.Tema,
                             Descripcion = l.Descripcion,
                             Usuario = l.Usuario,
                             NombreE = l.NombreEmpleado,
                             Estado = l.Estado.Descripcion,
                             Etiqueta = l.Etiqueta.Descripcion
                         }).ToList();

            pageSize = (pageSize ?? 50);
            page = (page ?? 1);
            ViewBag.PageSize = pageSize;
            var list = query.ToPagedList(page.Value, pageSize.Value);

            return View(list);
        }

        //Historial llamada pendiente
        public ActionResult Historial(int? id, int? pageSize, int? page)
        {
  
            var query = (from h in db.LlamadasHist
                         join l in db.Llamadas on h.LlamadaId equals l.LlamadaId
                         where 
                         //l.EstadoId == 2
                        // &&
                         l.LlamadaId == id
                         orderby l.Fecha descending
                         select new PendientesViewModel
                         {
                             LlamadaId = h.LlamadaId,
                             ClienteId = h.ClienteId,
                             NombreC = h.NombreCliente,
                             TiempoPostLlamado = h.TiempoPostLlamado,
                             Fecha = h.Fecha,
                             Hora = h.Hora,
                             Tema = h.Tema,
                             Descripcion = h.Descripcion,
                             Usuario = h.Usuario,
                             NombreE = h.NombreEmpleado,
                             Estado = h.Estado.Descripcion,
                             Etiqueta = h.Etiqueta.Descripcion
                         }).ToList();

            pageSize = (pageSize ?? 20);
            page = (page ?? 1);
            ViewBag.PageSize = pageSize;
            var list = query.ToPagedList(page.Value, pageSize.Value);

            return View(list);
        }

        public ActionResult BuscarLlamadas(int? pageSize, int? page)
        {

            var query = (from cl in db.Clientes
                         join p in db.Provincias on cl.ProvinciaId equals p.ProvinciaId
                         orderby cl.Nombre ascending
                         select new ClientesBusqueda
                         {
                             ClienteId = cl.ClienteId,
                             Nombre = cl.Nombre,
                             Domicilio = cl.Domicilio,
                             Localidad = cl.Localidad,
                             Provincia = p.NombreP,
                             Telefono = cl.Telefono,
                             Correo = cl.Correo,
                             FechaAlta = cl.FechaAlta,
                             FechaFundacion = cl.FechaFundacion
                         }).ToList();

            pageSize = (pageSize ?? 200);
            page = (page ?? 1);
            var list = query.ToPagedList(page.Value, pageSize.Value);

            return View(list);
        }

        public ActionResult BuscarTareasPendientes(int? pageSize, int? page)
        {

            var query = (from cl in db.Clientes
                         join p in db.Provincias on cl.ProvinciaId equals p.ProvinciaId
                         orderby cl.Nombre ascending
                         select new ClientesBusqueda
                         {
                             ClienteId = cl.ClienteId,
                             Nombre = cl.Nombre,
                             Domicilio = cl.Domicilio,
                             Localidad = cl.Localidad,
                             Provincia = p.NombreP,

PGMG/Views/Llamadas/BuscarLlamadas.cshtml
@using PagedList.Mvc;
@model PagedList.PagedList<PGMG.Models.ClientesBusqueda>

@{
    ViewBag.Title = "Lista de clientes";
}

<body class="w3">
    <div class="centrar">
        <h4>@ViewBag.Title</h4>
        <hr />
        <div class="row">
            <div class="col-sm-8">
            </div>
            <div class="col-sm-4">
                <input id="buscar" type="text" class="login" placeholder="Escriba algo para filtrar" />
            </div>
        </div>
        <br />

        <div class="rwd" id="recargar">
            <table id="clientes" class="table table-striped">
                <thead>
                    <tr>
                        <th style="text-align: center" onclick="sortTable(0)">Nombre</th>
                        <th style="text-align: center" onclick="sortTable(1)">Localidad</th>
                        <th style="text-align: center" onclick="sortTable(2)">Provincia</th>
                        <th style="text-align: center" onclick="sortTable(3)">Teléfono</th>
                        <th style="text-align: center" onclick="sortTable(4)">Fecha alta</th>
                        <th style="text-align: center">Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Nombre)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Localidad)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Provincia)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Telefono)
                            </td>
                            <td>
                                @item.FechaAlta.ToShortDateString()
                            </td>
                            <td class="desaparecerTemporalmente">
                                <a href="@Url.Action("ReporteLlamadas","Llamadas", new { id=item.ClienteId })" class="btn btn-default" target="_blank"
                                   data-toggle="tooltip" title="Ver llamadas del cliente">
                                    <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
            <a class="btn btn-default" onclick="exportTableToExcel('tblData')" title="Exportar a Excel">
                <span class="glyphicon glyphicon-save" aria-hidden="true"></span>
            </a>
            <a class="btn btn-default" onclick="exportTableToPDF()" title="Exportar a PDF">
                <span class="glyphicon glyphicon-save-file" aria-hidden="true"></span>
            </a>
            <br />
            <br />
            Página @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) de @Model.PageCount
            <br />
            Total clientes @Model.TotalItemCount

            @Html.PagedListPager(Model, page => Url.Action("Index", "Clientes",
            new { page, pageSize = ViewBag.PageSize}))
        </div>
    </div>
</body>


<div class="modal fade" id="modal-eliminar" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
        </div>
    </div>
</div>

@section Scripts{
    <script>
        var textbuscar = document.getElementById("buscar");
        textbuscar.onkeyup = function () {
            buscar(this);
        }
        function buscar(inputbuscar) {
            var valorabuscar = (inputbuscar.value).toLowerCase().trim();
            var tabla_tr = document.getElementById("clientes").getElementsByTagName("tbody")[0].rows;
            for (var i = 0; i < tabla_tr.length; i++) {
                var tr = tabla_tr[i];
                var textotr = (tr.innerText).toLowerCase();
                tr.className = (textotr.indexOf(valorabuscar) >= 0) ? "mostrar" : "ocultar";
            }
        }

        function sortTable(n) {
            var table, rows, switching, i, x, y, shouldSwitch, dir, switchcount = 0;
            table = document.getElementById("clientes");
            switching = true;
            dir = "asc";
            while (switching) {
                switching = false;
                rows = table.rows;
                for (i = 1; i < (rows.length - 1); i++) {
                    shouldSwitch = false;
                    x = rows[i].getElementsByTagName("TD")[n];
                    y = rows[i + 1].getElementsByTagName("TD")[n];
                    if (dir == "asc") {
                        if (x.innerHTML.toLowerCase() > y.innerHTML.toLowerCase()) {
                            shouldSwitch = true;
                            break;
                        }
                    } else if (dir == "desc") {
                        if (x.innerHTML.toLowerCase() < y.innerHTML.toLowerCase()) {
                            shouldSwitch = true;
                            break;
                        }
                    }
                }
                if (shouldSwitch) {
                    rows[i].parentNode.insertBefore(rows[i + 1], rows[i]);
                    switching = true;
                    switchcount++;
                } else {
                    if (switchcount == 0 && dir == "asc") {
                        dir = "desc";
                        switching = true;
                    }
                }
            }
        }

        function exportTableToExcel(tableID, filename = '') {
            var downloadLink;
            var dataType = 'application/vnd.ms-excel';
            var tableSelect = document.getElementById("clientes");
            var tableHTML = tableSelect.outerHTML.replace(/ /g, '%20');

            // Specify file name
            filename = filename ? filename + '.xls' : 'ListadoClientes.xls';

            // Create download link element
            downloadLink = document.createElement("a");

            document.body.appendChild(downloadLink);

            if (navigator.msSaveOrOpenBlob) {
                var blob = new Blob(['ufeff', tableHTML], {
                    type: dataType
                });
                navigator.msSaveOrOpenBlob(blob, filename);
            } else {
                // Create a link to the file
                downloadLink.href = 'data:' + dataType + ', ' + tableHTML;

                // Setting the file name
                downloadLink.download = filename;

                //triggering the function
                downloadLink.click();
            }
        }

        function exportTableToPDF() {
            //Seleccionamos TODOS los elementos que tienen esta clase "desaparecerTemporalmente y le damos un display none"
            $(".desaparecerTemporalmente").css("display", "none");
            html2canvas(document.getElementById('clientes'), {
                onrendered: function (canvas) {
                    var data = canvas.toDataURL();
                    var docDefinition = {
                        content: [{
                            image: data,
                            width: 500
                        }]
                    };
                    pdfMake.createPdf(docDefinition).download("Clientes.pdf");
                }
            });
            //Ahora que ya fue exportado, regresamos los botones a su sitio:
            $(".desaparecerTemporalmente").css("display", "");
        }
    </script>

}

PGMG/Views/Llamadas/BuscarTareasPendientes.cshtml
@using PagedList.Mvc;
@model PagedList.PagedList<PGMG.Models.ClientesBusqueda>

@{
    ViewBag.Title = "Lista de clientes";
}

<body class="w3">
    <div class="centrar">
        <h4>@ViewBag.Title</h4>
        <hr />
        <div class="row">
            <div class="col-sm-8">
            </div>
            <div class="col-sm-4">
                <input id="buscar" type="text" class="login" placeholder="Escriba algo para filtrar" />
            </div>
        </div>
        <br />

        <div class="rwd" id="recargar">
            <table id="clientes" class="table table-striped">
                <thead>
                    <tr>
                        <th style="text-align: center" onclick="sortTable(0)">Nombre</th>
                        <th style="text-align: center" onclick="sortTable(1)">Localidad</th>
                        <th style="text-align: center" onclick="sortTable(2)">Provincia</th>
                        <th style="text-align: center" onclick="sortTable(3)">Teléfono</th>
                        <th style="text-align: center" onclick="sortTable(4)">Fecha alta</th>
                        <th style="text-align: center">Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Nombre)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Localidad)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Provincia)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Telefono)
                            </td>
                            <td>
                                @item.FechaAlta.ToShortDateString()
                            </td>
                            <td class="desaparecerTemporalmente">
                                <a href="@Url.Action("ReportePendientes","Llamadas", new { id=item.ClienteId })" class="btn btn-default" target="_blank"
                                   data-toggle="tooltip" title="Ver pendientes del cliente">
                                    <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
            <a class="btn btn-default" onclick="exportTableToExcel('tblData')" title="Exportar a Excel">
                <span class="glyphicon glyphicon-save" aria-hidden="true"></span>
            </a>
            <a class="btn btn-default" onclick="exportTableToPDF()" title="Exportar a PDF">
                <span class="glyphicon glyphicon-save-file" aria-hidden="true"></span>
            </a>
            <br />
            <br />
            Página @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) de @Model.PageCount
            <br />
            Total clientes @Model.TotalItemCount

            @Html.PagedListPager(Model, page => Url.Action("Index", "Clientes",
            new { page, pageSize = ViewBag.PageSize}))
        </div>
    </div>
</body>


<div class="modal fade" id="modal-eliminar" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
        </div>
    </div>
</div>

@section Scripts{
    <script>


        var textbuscar = document.getElementById("buscar");
        textbuscar.onkeyup = function () {
            buscar(this);
        }
        function buscar(inputbuscar) {
            var valorabuscar = (inputbuscar.value).toLowerCase().trim();
            var tabla_tr = document.getElementById("clientes").getElementsByTagName("tbody")[0].rows;
            for (var i = 0; i < tabla_tr.length; i++) {
                var tr = tabla_tr[i];
                var textotr = (tr.innerText).toLowerCase();
                tr.className = (textotr.indexOf(valorabuscar) >= 0) ? "mostrar" : "ocultar";
            }
        }

        function sortTable(n) {
            var table, rows, switching, i, x, y, shouldSwitch, dir, switchcount = 0;
            table = document.getElementById("clientes");
            switching = true;
            dir = "asc";
            while (switching) {
                switching = false;
                rows = table.rows;
                for (i = 1; i < (rows.length - 1); i++) {
                    shouldSwitch = false;
                    x = rows[i].getElementsByTagName("TD")[n];
                    y = rows[i + 1].getElementsByTagName("TD")[n];
                    if (dir == "asc") {
                        if (x.innerHTML.toLowerCase() > y.innerHTML.toLowerCase()) {
                            shouldSwitch = true;
                            break;
                        }
                    } else if (dir == "desc") {
                        if (x.innerHTML.toLowerCase() < y.innerHTML.toLowerCase()) {
                            shouldSwitch = true;
                            break;
                        }
                    }
                }
                if (shouldSwitch) {
                    rows[i].parentNode.insertBefore(rows[i + 1], rows[i]);
                    switching = true;
                    switchcount++;
                } else {
                    if (switchcount == 0 && dir == "asc") {
                        dir = "desc";
                        switching = true;
                    }
                }
            }
        }

        function exportTableToExcel(tableID, filename = '') {
            var downloadLink;
            var dataType = 'application/vnd.ms-excel';
            var tableSelect = document.getElementById("clientes");
            var tableHTML = tableSelect.outerHTML.replace(/ /g, '%20');

            // Specify file name
            filename = filename ? filename + '.xls' : 'ListadoClientes.xls';

            // Create download link element
            downloadLink = document.createElement("a");

            document.body.appendChild(downloadLink);

            if (navigator.msSaveOrOpenBlob) {
                var blob = new Blob(['ufeff', tableHTML], {
                    type: dataType
                });
                navigator.msSaveOrOpenBlob(blob, filename);
            } else {
                // Create a link to the file
                downloadLink.href = 'data:' + dataType + ', ' + tableHTML;

                // Setting the file name
                downloadLink.download = filename;

                //triggering the function
                downloadLink.click();
            }
        }


        function exportTableToPDF() {
            //Seleccionamos TODOS los elementos que tienen esta clase "desaparecerTemporalmente y le damos un display none"
            $(".desaparecerTemporalmente").css("display", "none");
            html2canvas(document.getElementById('clientes'), {
                onrendered: function (canvas) {
                    var data = canvas.toDataURL();
                    var docDefinition = {
                        content: [{
                            image: data,
                            width: 500
                        }]
                    };
                    pdfMake.createPdf(docDefinition).download("Clientes.pdf");
                }
            });
            //Ahora que ya fue exportado, regresamos los botones a su sitio:
            $(".desaparecerTemporalmente").css("display", "");
        }
    </script>

}

PGMG/Views/Llamadas/Delete.cshtml
@model PGMG.Models.Llamada

@{
    ViewBag.Title = "Eliminar";
}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal"
        <span>&times;</span>
    </button>
</div>
<div class="modal-body">

    @using (Ajax.BeginForm("Delete", "Llamadas", null, new AjaxOptions
    {
        HttpMethod = "POST",
        Url = Url.Action("Delete", "Llamadas"),
        UpdateTargetId = "modal-content",
        OnSuccess = "closeModal",
        InsertionMode = InsertionMode.Replace
    },
    new { @class = "form-horizontal", role = "form", id = "frmCrear" }))
    {
        @Html.AntiForgeryToken()
    <div class="centrar">

        <h4>¿Desea eliminar la llamada?</h4>
        <br />
        <div class="form-group">
            <b>@Html.DisplayNameFor(model => model.Fecha):</b>
            @Model.Fecha.ToShortDateString()
        </div>
        <div class="form-group">
            <b>@Html.DisplayNameFor(model => model.Hora):</b>
            @Model.Hora.ToShortTimeString()
        </div>
        <div class="form-group">
            <b>@Html.DisplayNameFor(model => model.NombreCliente):</b>
            @Html.DisplayFor(model => model.NombreCliente)
        </div>
        <div class="form-group">
            <b>@Html.DisplayNameFor(model => model.NombreEmpleado):</b>
            @Html.DisplayFor(model => model.NombreEmpleado)
        </div>
        <div class="form-group">
            <b>@Html.DisplayNameFor(model => model.Tema):</b>
            @Html.DisplayFor(model => model.Tema)
        </div>
        <input type="submit" value="Eliminar" class="btn btn-default" data-target="#modal-eliminar" data-toggle="modal" />
        <input type="button" value="Cancelar" class="btn btn-default" data-target="#modal-eliminar" data-toggle="modal" />

    </div>
    }
</div>

@section Scripts{
    <script>

        function closeModal(data) {
            if (data.success) {
                $('#modal-eliminar').modal('hide');
                window.location.reload();
                window.location.href = "/Llamadas/index2";
            }
        }
    </script>
}