PGMG/Models/FormaDeComunicacion.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PGMG.Models
{
    public class FormaDeComunicacion
    {
        public int FormaDeComunicacionId { get; set; }
        public string Detalle { get; set; }
    }
}

PGMG/Controllers/FormaDeComunicacionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PGMG.Models;

namespace PGMG.Controllers
{
    [Authorize(Roles = "Administradora")]
    public class FormaDeComunicacionController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: FormaDeComunicacion
        public ActionResult Index()
        {
            return View(db.FormasDeComunicacion.ToList());
        }

        // GET: FormaDeComunicacion/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FormaDeComunicacion formaDeComunicacion = db.FormasDeComunicacion.Find(id);
            if (formaDeComunicacion == null)
            {
                return HttpNotFound();
            }
            return View(formaDeComunicacion);
        }

        // GET: FormaDeComunicacion/Create
        public ActionResult Create()
        {
            return PartialView();
        }

        // POST: FormaDeComunicacion/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "FormaDeComunicacionId,Detalle")] FormaDeComunicacion formaDeComunicacion)
        {
            if (ModelState.IsValid)
            {
                db.FormasDeComunicacion.Add(formaDeComunicacion);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(formaDeComunicacion);
        }

        // GET: FormaDeComunicacion/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FormaDeComunicacion formaDeComunicacion = db.FormasDeComunicacion.Find(id);
            if (formaDeComunicacion == null)
            {
                return HttpNotFound();
            }
            return PartialView(formaDeComunicacion);
        }

        // POST: FormaDeComunicacion/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "FormaDeComunicacionId,Detalle")] FormaDeComunicacion formaDeComunicacion)
        {
            if (ModelState.IsValid)
            {
                db.Entry(formaDeComunicacion).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(formaDeComunicacion);
        }

        // GET: FormaDeComunicacion/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FormaDeComunicacion formaDeComunicacion = db.FormasDeComunicacion.Find(id);
            if (formaDeComunicacion == null)
            {
                return HttpNotFound();
            }
            return PartialView(formaDeComunicacion);
        }

        // POST: FormaDeComunicacion/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            FormaDeComunicacion formaDeComunicacion = db.FormasDeComunicacion.Find(id);
            db.FormasDeComunicacion.Remove(formaDeComunicacion);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PGMG/Views/FormaDeComunicacion/Create.cshtml
@model PGMG.Models.FormaDeComunicacion

@{
    ViewBag.Title = "Cargar nueva forma de comunicación";
}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal"
            <span>&times;</span>
    </button>
</div>
<div class="modal-body centrar">
    <dl class="dl-horizontal">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(model => model.Detalle, htmlAttributes: new { @class = "control-label" })
                <br />
                @Html.EditorFor(model => model.Detalle, new { htmlAttributes = new { @class = "login" } })
                @Html.ValidationMessageFor(model => model.Detalle, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-default" data-target="#modal-crear" data-toggle="modal" />
                <input type="button" value="Cancelar" class="btn btn-default" data-target="#modal-crear" data-toggle="modal" />
            </div>
        }
    </dl>
</div>


@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        function closeModal(data) {
            if (data.success) {
                $('#modal-crear').modal('hide');
                window.location.href = "/FormaDeComunicacion/index";
            }
        }
    </script>
}

PGMG/Views/FormaDeComunicacion/Delete.cshtml
@model PGMG.Models.FormaDeComunicacion

@{
    ViewBag.Title = "Eliminar";
}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal"
        <span>&times;</span>
    </button>
</div>
<div class="modal-body">

    @using (Ajax.BeginForm("Delete", "FormaDeComunicacion", null, new AjaxOptions
    {
        HttpMethod = "POST",
        Url = Url.Action("Delete", "FormaDeComunicacion"),
        UpdateTargetId = "modal-content",
        OnSuccess = "closeModal",
        InsertionMode = InsertionMode.Replace
    },
    new { @class = "form-horizontal", role = "form", id = "frmCrear" }))
    {
        @Html.AntiForgeryToken()
        <div class="centrar">

            <h4>¿Desea eliminar la forma de comunicación?</h4>
            <br />

            <input type="submit" value="Eliminar" class="btn btn-default" data-target="#modal-eliminar" data-toggle="modal" />
            <input type="button" value="Cancelar" class="btn btn-default" data-target="#modal-eliminar" data-toggle="modal" />

        </div>
    }
</div>

@section Scripts{
    <script>

        function closeModal(data) {
            if (data.success) {
                $('#modal-eliminar').modal('hide');
                window.location.reload();
                window.location.href = "/FormaDeComunicacion/index";
            }
        }
    </script>
}

PGMG/Views/FormaDeComunicacion/Edit.cshtml
@model PGMG.Models.FormaDeComunicacion

@{
    ViewBag.Title = "Editar";
}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal"
            <span>&times;</span>
    </button>
</div>
<div class="modal-body centrar">
    <dl class="dl-horizontal">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.FormaDeComunicacionId)

            <div class="form-group">
                @Html.LabelFor(model => model.Detalle, htmlAttributes: new { @class = "control-label" })
                <br />
                @Html.EditorFor(model => model.Detalle, new { htmlAttributes = new { @class = "login" } })
                @Html.ValidationMessageFor(model => model.Detalle, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-default" data-target="#modal-detalles" data-toggle="modal"/>
                <input type="button" value="Cancelar" class="btn btn-default" data-target="#modal-detalles" data-toggle="modal" />
            </div>
        }
    </dl>
</div>


@section Scripts{
    <script>
        function closeModal(data) {
            if (data.success) {
                $('#modal-detalles').modal('hide');
                window.location.href = "/FormaDeComunicacion/index";
            }
        }
    </script>
}

PGMG/Views/FormaDeComunicacion/Index.cshtml
@model IEnumerable<PGMG.Models.FormaDeComunicacion>

@{
    ViewBag.Title = "Formas de comunicación";
}

<body class="w3">
    <div class="centrar">
        <h4>@ViewBag.Title</h4>
        <hr />
        <a href="@Url.Action("Create")" class="btn btn-default"
           data-target="#modal-crear" data-toggle="modal">
            Nueva forma de comunicación
        </a>
        <br /><br />

        <div class="table-responsive">
            <table id="comunicaciones" class="table table-striped">
                <thead>
                    <tr>
                        <th style="text-align: center" onclick="sortTable(0)">Descripción</th>
                        <th style="text-align: center">Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Detalle)
                            </td>
                            <td>
                                <a href="@Url.Action("Edit", new {id = item.FormaDeComunicacionId})" class="btn btn-default"
                                   data-target="#modal-detalles" data-toggle="modal" title="Editar forma de comunicación">
                                    <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                                </a>
                                <a href="@Url.Action("Delete", new { id=item.FormaDeComunicacionId })" class="btn btn-default"
                                   data-target="#modal-eliminar" data-toggle="modal" title="Eliminar forma de comunicación">
                                    <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</body>
<div class="modal fade" id="modal-eliminar" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
        </div>
    </div>
</div>
<div class="modal fade" id="modal-detalles" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
        </div>
    </div>
</div>
<div class="modal fade" id="modal-crear" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
        </div>
    </div>
</div>


@section Scripts{
    <script>
        function sortTable(n) {
            var table, rows, switching, i, x, y, shouldSwitch, dir, switchcount = 0;
            table = document.getElementById("comunicaciones");
            switching = true;
            dir = "asc";
            while (switching) {
                switching = false;
                rows = table.rows;
                for (i = 1; i < (rows.length - 1); i++) {
                    shouldSwitch = false;
                    x = rows[i].getElementsByTagName("TD")[n];
                    y = rows[i + 1].getElementsByTagName("TD")[n];
                    if (dir == "asc") {
                        if (x.innerHTML.toLowerCase() > y.innerHTML.toLowerCase()) {
                            shouldSwitch = true;
                            break;
                        }
                    } else if (dir == "desc") {
                        if (x.innerHTML.toLowerCase() < y.innerHTML.toLowerCase()) {
                            shouldSwitch = true;
                            break;
                        }
                    }
                }
                if (shouldSwitch) {
                    rows[i].parentNode.insertBefore(rows[i + 1], rows[i]);
                    switching = true;
                    switchcount++;
                } else {
                    if (switchcount == 0 && dir == "asc") {
                        dir = "desc";
                        switching = true;
                    }
                }
            }
        }
    </script>
}